import React, { useEffect, useState, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { supabase } from '../../lib/supabaseClient';
import { useAuth } from '../../context/AuthContext';
import {
  Database,
  RefreshCw,
  PlusCircle,
  ShieldCheck,
  AlertCircle,
  Lock,
  Search,
  Layers,
  HeartPulse,
  ClipboardList,
  Flame,
  PlaneTakeoff,
  CalendarDays,
  Vote,
  MessageSquareText,
  Briefcase,
  Stethoscope,
  BellRing,
  Award,
  Sparkles,
  ChevronDown,
  ChevronRight,
  ExternalLink,
  Trash2,
  Filter,
} from 'lucide-react';

interface TableDefinition {
  id: string;
  name: string;
  category: 'Telemetry & Biometrics' | 'Clinical & Assessments' | 'Operations & HR' | 'System & Feedback';
  description: string;
  icon: React.ElementType;
  primaryColumns: string[];
}

const TABLES: TableDefinition[] = [
  {
    id: 'profiles',
    name: 'User Profiles & Identity',
    category: 'Operations & HR',
    description: 'CAPF personnel military credentials, ranks, assigned force, unit, and RLS roles.',
    icon: Layers,
    primaryColumns: ['name', 'rank', 'service_number', 'force', 'unit', 'role', 'department'],
  },
  {
    id: 'wearable_telemetry',
    name: 'Wearable Biometrics',
    category: 'Telemetry & Biometrics',
    description: 'Daily IoT smart-band readings: Heart Rate (BPM), HRV (ms), SpO2, Sleep Hours, Stress Index.',
    icon: HeartPulse,
    primaryColumns: ['date', 'heart_rate', 'hrv', 'spo2', 'steps', 'sleep_hours', 'stress_index'],
  },
  {
    id: 'assessments',
    name: 'Clinical Screeners & PHQ-9',
    category: 'Clinical & Assessments',
    description: 'Voluntary behavioral surveys, MBI burnout inventories, and recovery recommendations.',
    icon: ClipboardList,
    primaryColumns: ['assessment_title', 'date', 'score', 'max_score', 'risk_level', 'status'],
  },
  {
    id: 'stress_metrics',
    name: 'Stress & Fatigue Metrics',
    category: 'Telemetry & Biometrics',
    description: 'Aggregated unit-level stress index, workload exposure hours, and burnout trajectory.',
    icon: Flame,
    primaryColumns: ['date', 'stress_score', 'workload_hours', 'burnout_risk', 'fatigue_index', 'source'],
  },
  {
    id: 'deployments',
    name: 'Field Deployments',
    category: 'Operations & HR',
    description: 'Operational rotations across Siachen, Leh-Ladakh, J&K, and high-altitude sectors.',
    icon: PlaneTakeoff,
    primaryColumns: ['project_name', 'location', 'deployment_type', 'stress_impact', 'status', 'start_date'],
  },
  {
    id: 'leave_records',
    name: 'Wellness & Leave Logs',
    category: 'Operations & HR',
    description: 'Wellness Recharge respites, medical convalescence, and commander approvals.',
    icon: CalendarDays,
    primaryColumns: ['leave_type', 'days', 'status', 'start_date', 'end_date', 'reason'],
  },
  {
    id: 'wellness_surveys',
    name: 'Pulse Surveys',
    category: 'Clinical & Assessments',
    description: 'Battalion-wide psychological safety, leadership trust, and field workload ratings.',
    icon: Vote,
    primaryColumns: ['title', 'category', 'status', 'overall_score', 'participation_rate', 'created_at'],
  },
  {
    id: 'survey_responses',
    name: 'Survey Responses',
    category: 'Clinical & Assessments',
    description: 'Confidential personnel feedback with 100% Differential Privacy protection.',
    icon: MessageSquareText,
    primaryColumns: ['survey_id', 'work_life_balance', 'psychological_safety', 'sentiment', 'created_at'],
  },
  {
    id: 'workload_records',
    name: 'Shift & Workload Allocation',
    category: 'Operations & HR',
    description: 'Weekly tactical tempo, capacity utilization percentage, and overtime thresholds.',
    icon: Briefcase,
    primaryColumns: ['assigned_tasks', 'completed_tasks', 'weekly_hours_logged', 'utilization_rate', 'intensity_level'],
  },
  {
    id: 'interventions',
    name: 'Medical & Rest Interventions',
    category: 'Operations & HR',
    description: 'Prescribed 48-hour clinical respites, counseling scripts, and restorative actions.',
    icon: Stethoscope,
    primaryColumns: ['title', 'category', 'urgency', 'status', 'target_unit', 'created_at'],
  },
  {
    id: 'welfare_alerts',
    name: 'Welfare & Tactical Alerts',
    category: 'System & Feedback',
    description: 'Predictive early warning signals generated by XGBoost and bio-telemetry anomalies.',
    icon: BellRing,
    primaryColumns: ['title', 'type', 'force', 'unit', 'resolved', 'created_at'],
  },
  {
    id: 'feedback',
    name: 'Platform Evaluations',
    category: 'System & Feedback',
    description: 'Evaluator and jury ratings on design, AI models, security, and strategic impact.',
    icon: Award,
    primaryColumns: ['evaluator_name', 'rating', 'category', 'comments', 'created_at'],
  },
];

export const SupabaseDataTab: React.FC = () => {
  const { session, supabaseUser, isAuthenticated, openAuthModal, user: localUser } = useAuth();

  const [selectedTable, setSelectedTable] = useState<TableDefinition>(TABLES[0]);
  const [data, setData] = useState<any[]>([]);
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [searchQuery, setSearchQuery] = useState<string>('');
  const [insertBusy, setInsertBusy] = useState<boolean>(false);
  const [insertMessage, setInsertMessage] = useState<string | null>(null);
  const [expandedRow, setExpandedRow] = useState<number | null>(null);

  // ── 1. Fetch Data Function (Guarded by Auth State) ───────────────────────────
  const fetchTableData = useCallback(async (tableId: string) => {
    // Only attempt to fetch data after confirming the user is logged in
    if (!isAuthenticated && !supabaseUser) {
      setData([]);
      setError('Authentication required. Please sign in to query this table under Row Level Security.');
      return;
    }

    setLoading(true);
    setError(null);
    setInsertMessage(null);

    try {
      console.log(`[SupabaseData] 📡 Fetching from table: "${tableId}"...`);
      const { data: records, error: fetchError } = await supabase
        .from(tableId)
        .select('*')
        .order('created_at', { ascending: false })
        .limit(50);

      if (fetchError) {
        // If sorting by created_at fails (e.g. table without created_at), retry plain select
        const { data: fallbackRecords, error: fallbackError } = await supabase
          .from(tableId)
          .select('*')
          .limit(50);

        if (fallbackError) {
          setError(fallbackError.message);
          setData([]);
        } else {
          setData(fallbackRecords || []);
        }
      } else {
        setData(records || []);
      }
    } catch (err: any) {
      setError(err?.message || 'An unexpected error occurred while querying the database.');
      setData([]);
    } finally {
      setLoading(false);
    }
  }, [isAuthenticated, supabaseUser]);

  // Refetch whenever active table changes or user auth changes
  useEffect(() => {
    fetchTableData(selectedTable.id);
  }, [selectedTable.id, fetchTableData]);

  // ── 2. Insert Sample Row for Live RLS Testing ────────────────────────────────
  const handleInsertSampleRow = async () => {
    if (!supabaseUser && !localUser) {
      openAuthModal();
      return;
    }

    setInsertBusy(true);
    setInsertMessage(null);

    const userId = supabaseUser?.id || localUser.id;
    const now = new Date();
    const dateStr = now.toISOString().split('T')[0];

    let rowData: any = null;

    switch (selectedTable.id) {
      case 'profiles':
        rowData = {
          id: userId,
          name: localUser.name || 'Sentinel Jawan',
          email: supabaseUser?.email || `${localUser.serviceNumber.toLowerCase()}@veerwell.gov.in`,
          rank: localUser.rank || 'Inspector',
          service_number: localUser.serviceNumber || `CRPF-${Math.floor(100000 + Math.random() * 900000)}`,
          force: localUser.force || 'CRPF',
          unit: localUser.unit || '142 Bn (Srinagar Sector)',
          role: localUser.role || 'personnel',
          department: 'Operations',
          designation: localUser.roleTitle || 'Tactical Recon Specialist',
          anonymized_id: localUser.anonymizedId || `CAPF-NODE-${Math.floor(1000 + Math.random() * 9000)}`,
        };
        break;

      case 'wearable_telemetry':
        rowData = {
          user_id: userId,
          date: dateStr,
          heart_rate: Math.floor(62 + Math.random() * 20),
          hrv: Math.floor(45 + Math.random() * 35),
          spo2: Number((96.5 + Math.random() * 2.5).toFixed(1)),
          steps: Math.floor(6500 + Math.random() * 6000),
          sleep_hours: Number((6.5 + Math.random() * 2.0).toFixed(1)),
          sleep_quality: Math.floor(70 + Math.random() * 25),
          stress_index: Math.floor(25 + Math.random() * 45),
          recovery_score: Math.floor(65 + Math.random() * 30),
          resting_heart_rate: Math.floor(58 + Math.random() * 10),
          calories: Math.floor(2100 + Math.random() * 500),
        };
        break;

      case 'assessments':
        rowData = {
          user_id: userId,
          assessment_code: 'PHQ-9',
          assessment_title: 'PHQ-9 Mental Stamina Screener',
          date: dateStr,
          score: Math.floor(4 + Math.random() * 10),
          max_score: 27,
          risk_level: 'Low',
          status: 'Completed',
          summary: 'Optimal mental vitality and resilience index recorded under clinical protocol.',
          recommendations: [
            'Maintain regular sleep schedule post shift',
            'Perform 4-4-4-4 Box Breathing on high-tempo duties',
          ],
        };
        break;

      case 'stress_metrics':
        rowData = {
          user_id: userId,
          department: 'Operations',
          role_title: localUser.rank || 'Frontline Sentinel',
          stress_score: Number((3.5 + Math.random() * 3.5).toFixed(1)),
          workload_hours: Math.floor(38 + Math.random() * 12),
          burnout_risk: 'Low',
          sleep_deficit_hrs: Number((Math.random() * 1.5).toFixed(1)),
          fatigue_index: Math.floor(35 + Math.random() * 30),
          date: dateStr,
          source: 'Wearable Telemetry',
        };
        break;

      case 'deployments':
        rowData = {
          user_id: userId,
          project_name: 'Operation Shanti Suraksha (Siachen Support)',
          role: localUser.rank || 'Inspector',
          start_date: dateStr,
          location: 'Leh-Ladakh Sector Command',
          deployment_type: 'High-Intensity Field',
          stress_impact: 'Moderate',
          status: 'Active',
          key_milestones: [
            'Phase 1: Readiness screener verified',
            'Phase 2: Bio-sensors synced to central command',
          ],
        };
        break;

      case 'leave_records':
        rowData = {
          user_id: userId,
          leave_type: 'Wellness Recharge',
          start_date: dateStr,
          end_date: new Date(Date.now() + 3 * 86400000).toISOString().split('T')[0],
          days: 3,
          status: 'Approved',
          reason: 'Proactive 3-day Wellness Recharge respite to prevent cumulative fatigue.',
          applied_date: dateStr,
        };
        break;

      case 'wellness_surveys':
        rowData = {
          title: 'Q3 High-Altitude Operational Resilience Check',
          description: 'Quarterly evaluation of field ergonomics and sleep recovery.',
          category: 'Workforce Culture',
          status: 'Active',
          overall_score: 84,
          participation_rate: 94.5,
        };
        break;

      case 'survey_responses':
        rowData = {
          survey_id: '00000000-0000-0000-0000-000000000001',
          user_id: userId,
          work_life_balance: 78,
          psychological_safety: 88,
          physical_environment: 82,
          peer_support: 92,
          leadership_empathy: 80,
          comment: 'The new wearable alerts have helped us pace our recovery shifts effectively.',
          sentiment: 'Positive',
        };
        break;

      case 'workload_records':
        rowData = {
          user_id: userId,
          assigned_tasks: 12,
          completed_tasks: 10,
          weekly_hours_logged: 41.5,
          capacity_hours: 40,
          utilization_rate: 104,
          overtime_flag: false,
          intensity_level: 'Optimal',
          sprint_status: 'In Progress',
          week_start: dateStr,
        };
        break;

      case 'interventions':
        rowData = {
          created_by: userId,
          target_user_id: userId,
          title: '48-Hour Recovery & Rehydration Protocol',
          target_unit: localUser.unit || '142 Bn Srinagar Sector',
          target_role: localUser.rank || 'Frontline Sentinel',
          urgency: 'Scheduled',
          category: 'Rest Rotation',
          description: 'Prescribed 48h active recovery and thermal sleep reset.',
          counseling_prompt: 'Conduct post-deployment debrief with Unit Medical Officer.',
          status: 'Active',
        };
        break;

      case 'welfare_alerts':
        rowData = {
          type: 'warning',
          title: 'High Shift Fatigue Warning',
          force: localUser.force || 'CRPF',
          unit: localUser.unit || '209 CoBRA Bn',
          message: 'Consecutive night shift HRV dip detected. Rest rotation recommended.',
          action_required: 'Authorize 24h wellness recovery rotation.',
          resolved: false,
        };
        break;

      case 'feedback':
        rowData = {
          user_id: userId,
          evaluator_name: localUser.name || 'Jury Member',
          evaluator_role: localUser.roleTitle || 'Commanding Officer',
          rating: 5,
          category: 'Security & Privacy',
          comments: 'Exceptional zero-trust RLS implementation with live database telemetry synchronization!',
        };
        break;

      default:
        rowData = { user_id: userId, created_at: new Date().toISOString() };
    }

    try {
      console.log(`[SupabaseData] ✍️ Inserting record into "${selectedTable.id}":`, rowData);
      const { data: inserted, error: insertError } = await supabase
        .from(selectedTable.id)
        .upsert(rowData)
        .select();

      if (insertError) {
        setInsertMessage(`❌ Insert failed: ${insertError.message}`);
      } else {
        setInsertMessage(`✅ Record inserted successfully! RLS authorized row.`);
        fetchTableData(selectedTable.id);
      }
    } catch (e: any) {
      setInsertMessage(`❌ Error: ${e.message}`);
    } finally {
      setInsertBusy(false);
    }
  };

  // Filter records based on search query
  const filteredData = data.filter((row) => {
    if (!searchQuery.trim()) return true;
    const q = searchQuery.toLowerCase();
    return Object.values(row).some((val) =>
      typeof val === 'string'
        ? val.toLowerCase().includes(q)
        : typeof val === 'number'
        ? String(val).includes(q)
        : false
    );
  });

  const ActiveIcon = selectedTable.icon;

  return (
    <div className="space-y-6">
      {/* ── Header Banner ──────────────────────────────────────────────────────── */}
      <div className="p-6 rounded-3xl bg-gradient-to-r from-olive-950 via-olive-900 to-olive-950 border border-accent-gold/40 shadow-2xl relative overflow-hidden">
        <div className="absolute top-0 right-0 w-96 h-96 bg-accent-gold/10 rounded-full blur-[100px] pointer-events-none" />

        <div className="relative z-10 flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2.5">
              <div className="p-2 rounded-xl bg-accent-gold/20 border border-accent-gold/50 text-accent-gold">
                <Database className="w-5 h-5" />
              </div>
              <h1 className="text-xl md:text-2xl font-black text-white tracking-tight">
                Live Database Explorer
              </h1>
              <span className="px-2.5 py-0.5 rounded-full text-[10px] font-mono font-bold bg-emerald-500/20 text-emerald-300 border border-emerald-500/40 flex items-center gap-1">
                <ShieldCheck className="w-3 h-3" />
                RLS Active
              </span>
            </div>
            <p className="text-xs text-olive-300 font-mono mt-1.5 max-w-2xl">
              Real-time query engine connected to your PostgreSQL instance. Records are strictly partitioned by
              Row Level Security policies according to military rank and user ownership.
            </p>
          </div>

          {/* Action Buttons */}
          <div className="flex items-center gap-2.5 flex-wrap">
            <button
              onClick={() => fetchTableData(selectedTable.id)}
              disabled={loading}
              className="px-3.5 py-2 rounded-xl bg-olive-900/90 hover:bg-olive-800 border border-olive-700/80 text-olive-200 hover:text-white text-xs font-bold font-mono flex items-center gap-2 transition-all disabled:opacity-50"
            >
              <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin text-accent-gold' : ''}`} />
              <span>{loading ? 'Querying…' : 'Refresh Table'}</span>
            </button>

            <button
              onClick={handleInsertSampleRow}
              disabled={insertBusy}
              className="px-4 py-2 rounded-xl bg-gradient-to-r from-accent-gold to-accent-saffron text-navy-950 text-xs font-black flex items-center gap-2 shadow-lg hover:shadow-accent-gold/20 hover:scale-[1.02] active:scale-[0.98] transition-all disabled:opacity-50"
            >
              <PlusCircle className="w-4 h-4" />
              <span>{insertBusy ? 'Writing…' : 'Insert Test Record'}</span>
            </button>
          </div>
        </div>

        {/* Feedback message */}
        {insertMessage && (
          <motion.div
            initial={{ opacity: 0, y: -5 }}
            animate={{ opacity: 1, y: 0 }}
            className={`mt-4 p-3 rounded-xl text-xs font-mono border flex items-center justify-between ${
              insertMessage.includes('✅')
                ? 'bg-emerald-950/80 border-emerald-500/40 text-emerald-300'
                : 'bg-rose-950/80 border-rose-500/40 text-rose-300'
            }`}
          >
            <span>{insertMessage}</span>
            <button onClick={() => setInsertMessage(null)} className="text-white/50 hover:text-white text-xs">
              ✕
            </button>
          </motion.div>
        )}
      </div>

      {/* ── Table Selector Grid ────────────────────────────────────────────────── */}
      <div className="space-y-2">
        <div className="flex items-center justify-between">
          <span className="text-xs font-bold text-olive-400 font-mono tracking-wider uppercase">
            Select PostgreSQL Table ({TABLES.length} available)
          </span>
          <span className="text-[11px] text-olive-400 font-mono">
            Active: <strong className="text-accent-gold">{selectedTable.id}</strong>
          </span>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-2.5">
          {TABLES.map((tbl) => {
            const Icon = tbl.icon;
            const isSelected = selectedTable.id === tbl.id;
            return (
              <button
                key={tbl.id}
                onClick={() => {
                  setSelectedTable(tbl);
                  setExpandedRow(null);
                  setSearchQuery('');
                }}
                className={`p-3 rounded-2xl border text-left transition-all flex flex-col justify-between ${
                  isSelected
                    ? 'bg-olive-900 border-accent-gold shadow-lg shadow-accent-gold/10'
                    : 'bg-olive-950/60 border-olive-800/80 hover:border-olive-700 hover:bg-olive-900/40'
                }`}
              >
                <div className="flex items-center justify-between mb-1.5">
                  <div
                    className={`p-1.5 rounded-lg ${
                      isSelected ? 'bg-accent-gold/20 text-accent-gold' : 'bg-olive-800/60 text-olive-400'
                    }`}
                  >
                    <Icon className="w-4 h-4" />
                  </div>
                  <span className="text-[9px] font-mono text-olive-500 truncate max-w-[80px]">
                    {tbl.category.split(' ')[0]}
                  </span>
                </div>
                <div>
                  <div className={`text-xs font-bold truncate ${isSelected ? 'text-accent-gold' : 'text-slate-200'}`}>
                    {tbl.name}
                  </div>
                  <div className="text-[10px] font-mono text-olive-400 truncate mt-0.5">{tbl.id}</div>
                </div>
              </button>
            );
          })}
        </div>
      </div>

      {/* ── Active Table Explorer Panel ────────────────────────────────────────── */}
      <div className="rounded-3xl bg-olive-950/80 border border-olive-800 shadow-2xl overflow-hidden backdrop-blur-xl">
        {/* Table Sub-header & Search Bar */}
        <div className="p-4 md:p-5 border-b border-olive-800/80 flex flex-col sm:flex-row sm:items-center justify-between gap-3 bg-olive-900/40">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-xl bg-accent-gold/20 border border-accent-gold/40 text-accent-gold">
              <ActiveIcon className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-sm md:text-base font-bold text-white">{selectedTable.name}</h2>
                <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-olive-800 text-olive-300 border border-olive-700">
                  public.{selectedTable.id}
                </span>
              </div>
              <p className="text-[11px] text-olive-400 font-sans mt-0.5">{selectedTable.description}</p>
            </div>
          </div>

          {/* Search Input */}
          <div className="relative min-w-[220px]">
            <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-olive-400" />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search records…"
              className="w-full pl-9 pr-4 py-2 rounded-xl bg-olive-950 border border-olive-700/80 focus:border-accent-gold text-white text-xs font-mono outline-none"
            />
          </div>
        </div>

        {/* ── 3. Content States: Loading, Error, Empty RLS Fallback, or Table View ── */}
        {loading ? (
          <div className="p-16 text-center space-y-4">
            <div className="w-10 h-10 border-2 border-accent-gold border-t-transparent rounded-full animate-spin mx-auto" />
            <div className="space-y-1">
              <p className="text-sm font-bold text-white">Executing Postgres Query on Database…</p>
              <p className="text-xs text-olive-400 font-mono">
                SELECT * FROM public.{selectedTable.id} (Row Level Security evaluated)
              </p>
            </div>
          </div>
        ) : error ? (
          <div className="p-8 md:p-12 text-center max-w-lg mx-auto space-y-4">
            <div className="w-12 h-12 rounded-2xl bg-rose-500/20 border border-rose-500/40 flex items-center justify-center text-rose-400 mx-auto">
              <AlertCircle className="w-6 h-6" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-white">Database Query Error</h3>
              <p className="text-xs text-rose-300 font-mono mt-1 leading-relaxed">{error}</p>
            </div>
            <div className="flex justify-center gap-3 pt-2">
              <button
                onClick={() => fetchTableData(selectedTable.id)}
                className="px-4 py-2 rounded-xl bg-olive-900 hover:bg-olive-800 border border-olive-700 text-white text-xs font-bold font-mono transition-colors"
              >
                Retry Query
              </button>
              {!isAuthenticated && (
                <button
                  onClick={openAuthModal}
                  className="px-4 py-2 rounded-xl bg-accent-gold text-navy-950 text-xs font-bold transition-all"
                >
                  Sign In to Authenticate
                </button>
              )}
            </div>
          </div>
        ) : filteredData.length === 0 ? (
          /* ── Empty State / RLS Fallback ────────────────────────────────────────── */
          <div className="p-12 md:p-16 text-center max-w-md mx-auto space-y-4">
            <div className="w-14 h-14 rounded-3xl bg-olive-900/80 border border-olive-700 flex items-center justify-center text-accent-gold mx-auto shadow-inner">
              <Lock className="w-7 h-7" />
            </div>
            <div className="space-y-1.5">
              <h3 className="text-sm font-bold text-white">No Accessible Records Found</h3>
              <p className="text-xs text-olive-300 leading-relaxed">
                Table <code className="text-accent-gold font-mono">public.{selectedTable.id}</code> currently has 0
                visible rows for your authenticated scope.
              </p>
              <div className="p-3 rounded-xl bg-olive-900/50 border border-olive-800 text-[11px] text-olive-400 text-left space-y-1 mt-3">
                <div className="font-bold text-olive-300 flex items-center gap-1.5">
                  <ShieldCheck className="w-3.5 h-3.5 text-emerald-400" />
                  <span>Row Level Security (RLS) Doctrine:</span>
                </div>
                <p>
                  • Personnel/Jawans can only read & write their own records (<code className="text-emerald-300">auth.uid() = user_id</code>).
                </p>
                <p>
                  • Commanders and Medical Officers can view unit-level aggregates and counseling prompts.
                </p>
              </div>
            </div>

            <div className="pt-3 flex justify-center gap-3">
              <button
                onClick={handleInsertSampleRow}
                disabled={insertBusy}
                className="px-4 py-2.5 rounded-xl bg-gradient-to-r from-accent-gold to-accent-saffron text-navy-950 text-xs font-black flex items-center gap-2 shadow-lg hover:shadow-accent-gold/20 transition-all"
              >
                <PlusCircle className="w-4 h-4" />
                <span>{insertBusy ? 'Writing…' : 'Insert Test Record Now'}</span>
              </button>
            </div>
          </div>
        ) : (
          /* ── Multi-Column Data Table ───────────────────────────────────────────── */
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse text-xs">
              <thead>
                <tr className="border-b border-olive-800/80 bg-olive-900/60 font-mono text-[11px] text-olive-300">
                  <th className="py-3 px-4 w-12 text-center">#</th>
                  {selectedTable.primaryColumns.map((col) => (
                    <th key={col} className="py-3 px-4 capitalize whitespace-nowrap font-bold">
                      {col.replace(/_/g, ' ')}
                    </th>
                  ))}
                  <th className="py-3 px-4 text-right">Raw JSON</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-olive-800/50 font-mono">
                {filteredData.map((row, idx) => {
                  const isExpanded = expandedRow === idx;
                  return (
                    <React.Fragment key={row.id || idx}>
                      <tr className="hover:bg-olive-900/30 transition-colors">
                        <td className="py-3 px-4 text-center text-olive-500">{idx + 1}</td>
                        {selectedTable.primaryColumns.map((col) => {
                          const val = row[col];
                          return (
                            <td key={col} className="py-3 px-4 text-slate-200 whitespace-nowrap">
                              {typeof val === 'boolean' ? (
                                <span
                                  className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                                    val ? 'bg-emerald-500/20 text-emerald-300' : 'bg-olive-800 text-olive-400'
                                  }`}
                                >
                                  {val ? 'TRUE' : 'FALSE'}
                                </span>
                              ) : typeof val === 'number' ? (
                                <span className="font-bold text-accent-gold">{val}</span>
                              ) : Array.isArray(val) ? (
                                <span className="text-olive-300">{val.length} item(s)</span>
                              ) : val ? (
                                <span className="truncate max-w-[200px] inline-block">{String(val)}</span>
                              ) : (
                                <span className="text-olive-600 italic">—</span>
                              )}
                            </td>
                          );
                        })}
                        <td className="py-3 px-4 text-right">
                          <button
                            onClick={() => setExpandedRow(isExpanded ? null : idx)}
                            className="p-1.5 rounded-lg bg-olive-900 hover:bg-olive-800 text-olive-400 hover:text-white transition-colors"
                          >
                            <ChevronDown
                              className={`w-3.5 h-3.5 transition-transform ${isExpanded ? 'rotate-180 text-accent-gold' : ''}`}
                            />
                          </button>
                        </td>
                      </tr>

                      {/* Expanded JSON Inspector Row */}
                      {isExpanded && (
                        <tr className="bg-olive-950/90">
                          <td colSpan={selectedTable.primaryColumns.length + 2} className="p-4">
                            <div className="rounded-xl bg-navy-950 p-3.5 border border-olive-800 text-[11px] font-mono text-emerald-300 overflow-x-auto max-h-60">
                              <pre>{JSON.stringify(row, null, 2)}</pre>
                            </div>
                          </td>
                        </tr>
                      )}
                    </React.Fragment>
                  );
                })}
              </tbody>
            </table>

            {/* Table Footer Summary */}
            <div className="p-3 border-t border-olive-800/80 bg-olive-900/30 flex items-center justify-between text-[11px] font-mono text-olive-400">
              <span>Showing {filteredData.length} of {data.length} row(s) returned from database</span>
              <span className="text-accent-gold">Ordered by created_at DESC • Limit 50</span>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
